name: .NET
on:
  push:
    branches: [ master ]
    paths-ignore:
    - 'README.md'  
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/AVPVideoPlayer.Wpf.sln
    - name: Build
      run: dotnet build --no-restore ./src/AVPVideoPlayer.Wpf.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal ./src/AVPVideoPlayer.Wpf.sln
